name: 02 - Workflow Events
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
schedule:
  - cron: '*/5 * * * *' # runs every day at midnight

workflow_dispatch: # allows to trigger workflow manually from github actions tab

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo " i'am running on push event ${{ github.event_name}} event"