name: 04 Using Actions
on:
  workflow_dispatch: # allows to trigger workflow manually from github actions tab
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

    build:

        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: .github/workflows/04-using-actions/react-app
        steps:  
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Printing node version
              run: ls .github/workflows
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '24.x'
            - name: Install dependencies
              run: npm clean-install
            - name: run unit tests
              run: npm test

    
           