name: 13 - using caching in github actions
on:
  workflow_dispatch: 
      inputs:
        use-cache:
          description: 'Use cache or not'
          type: boolean
          default: true
        node-version:
          description: 'Node version to use'
          type: choice
          options:
            - '16.x'
            - '18.x'
            - '20.x' 
            - '22.x'    
          default: '24.x'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: checkout codes
        uses: actions/checkout@v4
      - name: use node 24
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: install dependencies
       # if: ${{ github.event.inputs.use-cache = 'true' }}
        run: npm ci
      - name: Testing
        run: npm run test
      - name: build
        run: npm run build
      - name: deploying to np
        run: echo "deploying to non prod environment"

 